tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "surface-container": "#f0f4f8",
                "on-primary-container": "#003366",
                "primary-fixed-dim": "#b3d1ff",
                "primary-fixed": "#e6f0ff",
                "surface-bright": "#ffffff",
                "on-error": "#ffffff",
                "on-background": "#001a33",
                "surface-tint": "#0056b3",
                "secondary-container": "#e0e7ff",
                "on-surface": "#001a33",
                "on-secondary-fixed-variant": "#374151",
                "error": "#dc2626",
                "on-primary-fixed": "#001a33",
                "surface-container-highest": "#e5e7eb",
                "surface-container-low": "#f9fafb",
                "on-secondary-container": "#0c1f32",
                "inverse-surface": "#111827",
                "surface-container-high": "#f3f4f6",
                "error-container": "#fee2e2",
                "on-primary-fixed-variant": "#193d5e",
                "outline-variant": "#d1d5db",
                "inverse-on-surface": "#f9fafb",
                "on-tertiary": "#ffffff",
                "tertiary-fixed-dim": "#94a3b8",
                "primary": "#204e79",
                "surface-variant": "#f1f5f9",
                "secondary": "#475569",
                "on-error-container": "#7f1d1d",
                "surface": "#ffffff",
                "secondary-fixed": "#e2e8f0",
                "tertiary": "#204e79",
                "background": "#ffffff",
                "primary-container": "#e6f0ff",
                "on-secondary-fixed": "#0f172a",
                "on-secondary": "#ffffff",
                "on-primary": "#ffffff",
                "on-tertiary-fixed": "#0f172a",
                "on-surface-variant": "#4b5563",
                "on-tertiary-container": "#204e79",
                "secondary-fixed-dim": "#cbd5e1",
                "inverse-primary": "#93c5fd",
                "tertiary-fixed": "#cbd5e1",
                "tertiary-container": "#e6f0ff",
                "surface-container-lowest": "#ffffff",
                "outline": "#9ca3af",
                "surface-dim": "#f3f4f6",
                "on-tertiary-fixed-variant": "#334155"
            },
            "borderRadius": {
                "DEFAULT": "0.375rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px"
            },
            "spacing": {
                "section-gap": "120px",
                "gutter": "32px",
                "stack-md": "16px",
                "margin": "24px",
                "container-max": "1280px",
                "element-gap": "24px",
                "stack-sm": "8px"
            },
            "fontFamily": {
                "body-lg": ["Inter"],
                "headline-md": ["Inter"],
                "headline-sm": ["Inter"],
                "button": ["Inter"],
                "display-xl": ["Inter"],
                "body-md": ["Inter"],
                "label-caps": ["Inter"],
                "display-lg": ["Inter"],
                "body-sm": ["Inter"]
            },
            "fontSize": {
                "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
                "headline-md": ["32px", { "lineHeight": "1.3", "fontWeight": "600" }],
                "headline-sm": ["24px", { "lineHeight": "1.4", "fontWeight": "600" }],
                "button": ["15px", { "lineHeight": "1", "fontWeight": "600" }],
                "display-xl": ["60px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
                "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
                "label-caps": ["12px", { "lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "700" }],
                "display-lg": ["48px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700" }],
                "body-sm": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }]
            }
        },
    },
};
